version: '2.1'
services:
  gateway:
    image: ${IMAGE_NAME:-apicast-test}
    depends_on:
    - redis
    - echo
    env_file: .env
    environment:
      THREESCALE_PORTAL_ENDPOINT: http://echo:8081/config/
  echo:
    image: ${IMAGE_NAME:-apicast-test}
    environment:
      APICAST_CONFIGURATION_LOADER: test
      APICAST_MANAGEMENT_API: debug
    command: bin/apicast
    ports:
      - '8081'
  dev:
    image: ${IMAGE_NAME:-apicast-test}
    depends_on:
    - redis
    ports:
      - "8080:8080"
      - "8090:8090"
    volumes:
      - .:/opt/app-root/src
    env_file: .env
    environment:
      TEST_NGINX_BINARY: openresty
      TEST_NGINX_REDIS_HOST: redis
    dns_search:
      - example.com
  test:
    image: ${IMAGE_NAME:-apicast-test}
    depends_on:
      - gateway
    entrypoint: ""
    dns: 127.0.0.1
    environment:
      APICAST_MANAGEMENT_API: debug
      APICAST_LOG_LEVEL: debug
      APICAST_CONFIGURATION_LOADER: test
    dns_search:
      - example.com
  prove:
    image: ${IMAGE_NAME:-apicast-test}
    user: root
    environment:
      TEST_NGINX_BINARY: openresty
      TEST_NGINX_REDIS_HOST: redis
    command: "sh -ec '$$TEST_NGINX_BINARY -V; cd ; /usr/libexec/s2i/entrypoint make prove; exit $$?'"
    dns_search:
      - example.com
    depends_on:
      - redis
    volumes_from:
    - container:${COMPOSE_PROJECT_NAME:-apicast_build_0}-source
  redis:
    image: redis
  keycloak:
    image: jboss/keycloak:3.1.0.Final
    environment:
      KEYCLOAK_USER: keycloak
      KEYCLOAK_PASSWORD: keycloak
      KEYCLOAK_LOGLEVEL: INFO
    ports:
      - "8080"
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411
